version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:latest
      - image: redis
    environment:
      GOPATH: /home/circleci/go
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}
      - run:
          name: Install Go and LD Relay
          command: |
            wget https://dl.google.com/go/go1.12.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.12.linux-amd64.tar.gz
            echo 'export PATH="$PATH:/usr/local/go/bin"' >> $BASH_ENV
      - run: go get -u gopkg.in/launchdarkly/ld-relay.v5/...
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r dev-requirements.txt
            pip install -e .
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: test rc command
          command: |
            . venv/bin/activate
            rc
      - run:
          name: Generate Redis Relay Config
          command: |
            . venv/bin/activate
            rc generate-relay-config -p support-service -s redis
      - run:
          name: Start LD Relay
          command: $GOPATH/bin/ld-relay --config ./ld-relay.conf
          background: true
      - run:
          name: Generate DynamoDB Relay Config
          command: |
            . venv/bin/activate
            rc generate-relay-config -p support-service -s dynamodb
      - run:
          name: Start LD Relay
          command: $GOPATH/bin/ld-relay --config ./ld-relay.conf
          background: true
      - run:
          name: Run Test Suite
          command: |
            . venv/bin/activate
            make test
      - run:
          name: Run Integration Tests
          command: |
            . venv/bin/activate
            make integration
      - run:
          name: Upload Code Coverage
          command: |
            . venv/bin/activate
            codecov
      - run:
          name: Generate Documentation
          command: |
            . venv/bin/activate
            make docs
      - store_artifacts:
          path: docs/_build/html
  test-python-install:
    parameters:
      version:
        type: string
        default: latest
    docker:
      - image: circleci/python:<< parameters.version >>
      - image: redis
    environment:
      GOPATH: /home/circleci/go
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}
      - run:
          name: Install Go and LD Relay
          command: |
            wget https://dl.google.com/go/go1.12.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.12.linux-amd64.tar.gz
            echo 'export PATH="$PATH:/usr/local/go/bin"' >> $BASH_ENV
      - run: go get -u gopkg.in/launchdarkly/ld-relay.v5/...
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r dev-requirements.txt
            pip install -e .
      - run:
          name: test rc command
          command: |
            . venv/bin/activate
            rc
      - run:
          name: Generate Redis Relay Config
          command: |
            . venv/bin/activate
            rc generate-relay-config -p support-service -s redis
      - run:
          name: Start LD Relay
          command: $GOPATH/bin/ld-relay --config ./ld-relay.conf
          background: true
      - run:
          name: Generate DynamoDB Relay Config
          command: |
            . venv/bin/activate
            rc generate-relay-config -p support-service -s dynamodb
      - run:
          name: Start LD Relay
          command: $GOPATH/bin/ld-relay --config ./ld-relay.conf
          background: true
      - run:
          name: Run Test Suite
          command: |
            . venv/bin/activate
            make test
      - run:
          name: Run Integration Tests
          command: |
            . venv/bin/activate
            make integration
      - run:
          name: Smoke Test Install
          command: |
            sudo pip3 install relaycommander
  deploy:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r dev-requirements.txt
            pip install -e .
      - run:
          name: verify git tag vs. version
          command: |
            . venv/bin/activate
            python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = mpartida" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            . venv/bin/activate
            python setup.py sdist bdist_wheel
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test-python-install:
          name: test-python-35
          version: "3.5"
          requires:
            - build
      - test-python-install:
          name: test-python-36
          version: "3.6"
          requires:
            - build
      - test-python-install:
          name: test-python-37
          version: "3.7"
          requires:
            - build
      - deploy:
          requires:
            - build
            - test-python-35
            - test-python-36
            - test-python-37
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
