version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:latest
      - image: redis
    environment:
      GOPATH: /home/circleci/go
    steps:
      - checkout
      - run:
          name: Install Go and LD Relay
          command: |
            wget https://dl.google.com/go/go1.12.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.12.linux-amd64.tar.gz
            echo 'export PATH="$PATH:/usr/local/go/bin"' >> $BASH_ENV
      - run: go get -u gopkg.in/launchdarkly/ld-relay.v5/...
      - run: pipenv install -d -e .
      - run: pipenv run rc
      - run:
          name: Run Test Suite
          command: |
            pipenv run make test
      - run:
          name: Generate Relay Config
          command: pipenv run generate-relay-config -p support-service
      - run:
          name: Start LD Relay
          command: $GOPATH/bin/ld-relay --config ./ld-relay.conf
          background: true
      - run:
          name: Run Integration Tests
          command: pipenv run make integration
      - run: pipenv run codecov
  test-python-install:
    parameters:
      version:
        type: string
        default: latest
    docker:
      - image: circleci/python:<< parameters.version >>
      - image: redis
    environment:
      GOPATH: /home/circleci/go
    steps:
      - checkout
      - run:
          name: Install Go
          command: |
            wget https://dl.google.com/go/go1.12.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.12.linux-amd64.tar.gz
            echo 'export PATH="$PATH:/usr/local/go/bin"' >> $BASH_ENV
      - run: go get -u gopkg.in/launchdarkly/ld-relay.v5/...
      - run: pipenv install -d -e .
      - run: pipenv run rc
      - run:
          name: Run Test Suite
          command: |
            pipenv run make test
      - run:
          name: Generate Relay Config
          command: pipenv run generate-relay-config -p support-service
      - run:
          name: Start LD Relay
          command: $GOPATH/bin/ld-relay --config ./ld-relay.conf
          background: true
      - run:
          name: Run Integration Tests
          command: pipenv run make integration
      - run:
          name: Smoke Test Install
          command: |
            python --version
            sudo pip3 install relaycommander
  deploy:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: install python dependencies
          command: |
            pipenv install -e .
            pipenv install twine
      - run:
          name: verify git tag vs. version
          command: |
            pipenv run python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = mpartida" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            pipenv run python setup.py sdist bdist_wheel
      - run:
          name: upload to pypi
          command: |
            pipenv run twine upload dist/*

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test-python-install:
          name: test-python-35
          version: "3.5"
          requires:
            - build
      - test-python-install:
          name: test-python-36
          version: "3.6"
          requires:
            - build
      - test-python-install:
          name: test-python-37
          version: "3.7"
          requires:
            - build
      - deploy:
          requires:
            - build
            # Enable this after we publish the initial multi-version
            # package. Prior to 0.0.11 we supported 3.6 only.
            # - test-python-35
            # - test-python-36
            # - test-python-37
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/